services:
  - name: express-backend
    type: web
    runtime: node
    repo: https://github.com/KetanHegde/coupon_management
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
