services:
  - name: coupon_management
    type: web
    runtime: node
    repo: https://github.com/KetanHegde/coupon_management
    plan: free
    buildCommand: cd coupon_backend && npm install
    startCommand: cd coupon_backend && node start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
